# Using DataBase customer_behaviour
USE customer_behaviour; 

#Samle Query
SELECT * FROM customer LIMIT 5;

# Q1. What is the Revenue generated by MALE & FEMALE customers?
SELECT gender, SUM(purchase_amount) AS revenue
FROM customer
GROUP BY gender;

# Q2. Which customers used a discount and still spent more than the Avg_purchase_amount?
SELECT customer_id, ROUND(AVG(purchase_amount),2) as Avg_purchase_amount
from customer
WHERE discount_applied = "yes" AND (SELECT purchase_amount > Avg(purchase_amount) FROM customer);

# Q3. Which are the top 5 products with the highest Avg Review Rating?
SELECT item_purchased, ROUND(AVG(review_rating),2) as Avg_review_rating
FROM customer
group by item_purchased
order by Avg_review_rating desc
LIMIT 5;

# Q4. Compare the Avg_purchase_amount between Standard and Express shipping.
SELECT shipping_type, ROUND(AVG(purchase_amount),2) as Avg_purchase_amount
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

# Q5. Do Subscribed customers spend more? compare Avg_spend between subscribers and non-subscribers.
SELECT subscription_status,
COUNT(customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) as avg_spend,
ROUND(SUM(purchase_amount),2) as total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue, avg_spend desc;

# Q6. Which 5 products have the highest percentage of purchases with discounts applied
SELECT item_purchased, 
ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
from customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

# Q7. segment customers in to New,Returning and Loyal based on their total no of previous purchases
# and show the count of each segment
WITH customer_type as(
SELECT customer_id,previous_purchases,
CASE 
	WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
	END AS customer_segment
FROM customer
)
SELECT customer_segment, COUNT(*) AS 'No_of_customers'
FROM customer_type
GROUP BY customer_segment;

# Q8. what are the top3 most purchased products within each catogery
with item_counts as (
SELECT category, item_purchased,
COUNT(customer_id) AS total_orders,
ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
FROM customer
GROUP BY category, item_purchased
)

SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;

#Q9. Are customers who are repeate buyers (morethan 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
count(customer_id) as repeate_buyers
from customer 
where previous_purchases > 5
group by subscription_status;

#Q10. What is the revenue contribution of each age group?
SELECT age_group, SUM(purchase_amount) as total_revenue
from customer 
GROUP BY age_group
ORDER BY total_revenue DESC;





